Balance class backport - fix C++17 related build errors
When backporting the Balance class implementation from Android 10,
below build errors occur, which are related to C++17 standard:

 error: nested namespace definition is a C++17 extension
 error: no member named 'size' in namespace 'std'

Fix above build errors by adapting the syntax accordingly.

Change-Id: If1fc9cc34df0994bde062e9c0620c0f8de437b6a